main_x_fixbits = solver.IntVar(0, 27, 'main_x_fixbits')
main_x_fixp = solver.IntVar(0, 1, 'main_x_fixp')
main_x_float = solver.IntVar(0, 1, 'main_x_float')
main_x_double = solver.IntVar(0, 1, 'main_x_double')
solver.Add( + (1)*main_x_fixp + (1)*main_x_float + (1)*main_x_double==1)
solver.Add( + (1)*main_x_fixbits + (-10000)*main_x_fixp<=0)
main_y_fixbits = solver.IntVar(0, 27, 'main_y_fixbits')
main_y_fixp = solver.IntVar(0, 1, 'main_y_fixp')
main_y_float = solver.IntVar(0, 1, 'main_y_float')
main_y_double = solver.IntVar(0, 1, 'main_y_double')
solver.Add( + (1)*main_y_fixp + (1)*main_y_float + (1)*main_y_double==1)
solver.Add( + (1)*main_y_fixbits + (-10000)*main_y_fixp<=0)
main_x_add_fixbits = solver.IntVar(0, 27, 'main_x_add_fixbits')
main_x_add_fixp = solver.IntVar(0, 1, 'main_x_add_fixp')
main_x_add_float = solver.IntVar(0, 1, 'main_x_add_float')
main_x_add_double = solver.IntVar(0, 1, 'main_x_add_double')
solver.Add( + (1)*main_x_add_fixp + (1)*main_x_add_float + (1)*main_x_add_double==1)
solver.Add( + (1)*main_x_add_fixbits + (-10000)*main_x_add_fixp<=0)
C1_main_x_add = solver.IntVar(0, 1, 'C1_main_x_add')
C2_main_x_add = solver.IntVar(0, 1, 'C2_main_x_add')
solver.Add( + (1)*main_x_fixbits + (-1)*main_x_add_fixbits + (-10000)*C1_main_x_add<=0)
solver.Add( + (-1)*main_x_fixbits + (1)*main_x_add_fixbits + (-10000)*C2_main_x_add<=0)
C3_main_x_add = solver.IntVar(0, 1, 'C3_main_x_add')
C4_main_x_add = solver.IntVar(0, 1, 'C4_main_x_add')
C5_main_x_add = solver.IntVar(0, 1, 'C5_main_x_add')
C6_main_x_add = solver.IntVar(0, 1, 'C6_main_x_add')
C7_main_x_add = solver.IntVar(0, 1, 'C7_main_x_add')
C8_main_x_add = solver.IntVar(0, 1, 'C8_main_x_add')
solver.Add( + (1)*main_x_fixp + (1)*main_x_add_float + (-1)*C3_main_x_add<=1)
solver.Add( + (1)*main_x_float + (1)*main_x_add_fixp + (-1)*C4_main_x_add<=1)
solver.Add( + (1)*main_x_fixp + (1)*main_x_add_double + (-1)*C5_main_x_add<=1)
solver.Add( + (1)*main_x_double + (1)*main_x_add_fixp + (-1)*C6_main_x_add<=1)
solver.Add( + (1)*main_x_float + (1)*main_x_add_double + (-1)*C7_main_x_add<=1)
solver.Add( + (1)*main_x_double + (1)*main_x_add_float + (-1)*C8_main_x_add<=1)
main_y_add_fixbits = solver.IntVar(0, 27, 'main_y_add_fixbits')
main_y_add_fixp = solver.IntVar(0, 1, 'main_y_add_fixp')
main_y_add_float = solver.IntVar(0, 1, 'main_y_add_float')
main_y_add_double = solver.IntVar(0, 1, 'main_y_add_double')
solver.Add( + (1)*main_y_add_fixp + (1)*main_y_add_float + (1)*main_y_add_double==1)
solver.Add( + (1)*main_y_add_fixbits + (-10000)*main_y_add_fixp<=0)
C1_main_y_add = solver.IntVar(0, 1, 'C1_main_y_add')
C2_main_y_add = solver.IntVar(0, 1, 'C2_main_y_add')
solver.Add( + (1)*main_y_fixbits + (-1)*main_y_add_fixbits + (-10000)*C1_main_y_add<=0)
solver.Add( + (-1)*main_y_fixbits + (1)*main_y_add_fixbits + (-10000)*C2_main_y_add<=0)
C3_main_y_add = solver.IntVar(0, 1, 'C3_main_y_add')
C4_main_y_add = solver.IntVar(0, 1, 'C4_main_y_add')
C5_main_y_add = solver.IntVar(0, 1, 'C5_main_y_add')
C6_main_y_add = solver.IntVar(0, 1, 'C6_main_y_add')
C7_main_y_add = solver.IntVar(0, 1, 'C7_main_y_add')
C8_main_y_add = solver.IntVar(0, 1, 'C8_main_y_add')
solver.Add( + (1)*main_y_fixp + (1)*main_y_add_float + (-1)*C3_main_y_add<=1)
solver.Add( + (1)*main_y_float + (1)*main_y_add_fixp + (-1)*C4_main_y_add<=1)
solver.Add( + (1)*main_y_fixp + (1)*main_y_add_double + (-1)*C5_main_y_add<=1)
solver.Add( + (1)*main_y_double + (1)*main_y_add_fixp + (-1)*C6_main_y_add<=1)
solver.Add( + (1)*main_y_float + (1)*main_y_add_double + (-1)*C7_main_y_add<=1)
solver.Add( + (1)*main_y_double + (1)*main_y_add_float + (-1)*C8_main_y_add<=1)
main_add_fixbits = solver.IntVar(0, 26, 'main_add_fixbits')
main_add_fixp = solver.IntVar(0, 1, 'main_add_fixp')
main_add_float = solver.IntVar(0, 1, 'main_add_float')
main_add_double = solver.IntVar(0, 1, 'main_add_double')
solver.Add( + (1)*main_add_fixp + (1)*main_add_float + (1)*main_add_double==1)
solver.Add( + (1)*main_add_fixbits + (-10000)*main_add_fixp<=0)
solver.Add( + (1)*main_x_add_fixp + (-1)*main_y_add_fixp==0)
solver.Add( + (1)*main_x_add_float + (-1)*main_y_add_float==0)
solver.Add( + (1)*main_x_add_double + (-1)*main_y_add_double==0)
solver.Add( + (1)*main_x_add_fixbits + (-1)*main_y_add_fixbits==0)
solver.Add( + (1)*main_x_add_fixp + (-1)*main_add_fixp==0)
solver.Add( + (1)*main_x_add_float + (-1)*main_add_float==0)
solver.Add( + (1)*main_x_add_double + (-1)*main_add_double==0)
solver.Add( + (1)*main_x_add_fixbits + (-1)*main_add_fixbits==0)
solver.Minimize( + (-1)*main_x_fixbits + (-149)*main_x_float + (-1074)*main_x_double + (-1)*main_y_fixbits + (-149)*main_y_float + (-1074)*main_y_double + (0.5)*C1_main_x_add + (0.5)*C2_main_x_add + (1)*C3_main_x_add + (1)*C4_main_x_add + (1)*C5_main_x_add + (1)*C6_main_x_add + (1)*C7_main_x_add + (1)*C8_main_x_add + (0.5)*C1_main_y_add + (0.5)*C2_main_y_add + (1)*C3_main_y_add + (1)*C4_main_y_add + (1)*C5_main_y_add + (1)*C6_main_y_add + (1)*C7_main_y_add + (1)*C8_main_y_add + (-1)*main_add_fixbits + (-20)*main_add_float + (-49)*main_add_double + (1)*main_add_fixp + (4)*main_add_float + (6)*main_add_double)

# Model declaration end.